baseURL = 'https://www.betoissues.com/'
languageCode = 'en-us'
title = "betoissues"
theme = "smol"
enableRobotsTXT = false
#canonifyurls = true

[pagination]
  disableAliases = false
  pagerSize = 25
  path = 'page'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[markup]
defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = true
    style = 'bw'
    tabWidth = 4
    wrapperClass = 'highlight'

# Parameters
[params]
    description = "my nerd corner, notes and dev logs directly from my obsidian vault"
    author = "Alberto Castillo"
    dateFmt = "2006-01-02"
    customCss = ["css/custom.css"]
    images = ['betoissues_default_square.png', 'profile.jpg']
    title = 'betoissues'
    [params.social]
        twitter = 'betoissues'

# Header
[menu]

[[menu.main]]
    url = "/log/"
    name = "log"
    weight = 1

[[menu.main]]
    url = "/notes/"
    name = "notes"
    weight = 2

[[menu.main]]
    url = "/links/"
    name = "links"
    weight = 3

# Footer
[[menu.footer]]
    name = "github"
    url = "https://github.com/betoissues"
    weight = 1

[[menu.footer]]
    name = "gotosocial"
    url = "https://gts.nixden.net/@beto"
    weight = 2

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = []
  term = []
