baseURL = 'https://notes.betoissues.com/'
languageCode = 'en-us'
title = "betoissues"
theme = "smol"
enableRobotsTXT = false
#canonifyurls = true

[markup]
defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = true
    style = 'gruvbox'
    tabWidth = 4

# Parameters
[params]
    description = "my nerd corner, notes and dev logs directly from my obsidian vault"
    author = "betoissues"
    dateFmt = "2006-01-02"
    customCss = ["css/custom.css"]

# Header
[menu]

[[menu.main]]
    url = "/log/"
    name = "log"
    weight = 1

[[menu.main]]
    url = "/notes/"
    name = "notes"
    weight = 2

[[menu.main]]
    url = "/links/"
    name = "links"
    weight = 3

# Footer
[[menu.footer]]
    name = "github"
    url = "https://github.com/betoissues"
    weight = 1

[[menu.footer]]
    name = "mastodon"
    url = "https://fosstodon.org/@betoissues"
    weight = 2

[[menu.footer]]
    url = "https://www.betoissues.com"
    name = "main blog"
    weight = 3

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = []
  term = []
